### ISSUE TITLE
[FEAT]: While Spreadhseet Upload, can we use Upload functionality instead of Create?

### ISSUE THREAD

**Issue by jaydeepgirigoswami** [spreadsheetimporter/ui5-cc-spreadsheetimporter#516]
### Description

Hello Marian,

Hope you are doing well!!!

I am using UI5-CC-SPREADHSHEETIMPORTER.

Can we add a feature which will Update/modify the record which are already in the Database instead of trying to Create it always? 

For E.g. I have a Material Number and it's description as field. Material Number is the primary key.
Now if I change the Description in the excel file and upload it using Spreadsheet uploader. it says entity already exist.

"We need it to update only the Description".

Do we already have a functionality in which we can use Update/Modify the records or the functionality is yet to be implemented?

Thanks and Regards,
Jaydeepgiri Goswami

**Comment by marianfoo** [comment]
Hi @jaydeepgirigoswami 
update and delete is planned to be in the upcoming paid version of the Spreadsheet Importer.

**Comment by jaydeepgirigoswami** [comment]
Hello @marianfoo,

Thanks for the information, by when can we expect the paid version to be available to the customers?
We have implemented the Standard version and will also looking forward for the paid one once available.

Thanks and Regards,
Jaydeepgiri Goswami

**Comment by marianfoo** [comment]
Hi @jaydeepgirigoswami 
Due to professional and private reasons, the release has been delayed and I cannot currently give a date.
The current goal is to bring the community version to 1.0.
After that comes the Pro Edition.

Regards
Marian
