### ISSUE TITLE
[Bug]: SSL error on Cloudflare

### ISSUE THREAD

**Issue by uxkjaer** [spreadsheetimporter/ui5-cc-spreadsheetimporter#522]
### OData Version

OData V2

### Draft

not relevant

### Scenario

Documentation

### Environment

All

### What happened?

Just wanted to point this out to you. Thanks for an amazing component!
https://docs.spreadsheet-importer.com/pages/GettingStarted/#starting-with-fiori-elements-odata-v2

![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/8186370/18d25646-4d2d-4557-b0d5-0899b034dd4d)

### Relevant log output

```shell
n/a
```

### Spreadsheet Component Init

```js
n/a
```

**Comment by marianfoo** [comment]
Thanks @uxkjaer !
certificate is managed by GitHub pages
Some hiccup there, is fixed
