### ISSUE TITLE
With reference to - Module Upload Error #544 

### ISSUE THREAD

**Issue by RaghavendraMarelle** [spreadsheetimporter/ui5-cc-spreadsheetimporter#569]
### OData Version

OData V2

### Draft

Yes

### Scenario

Facing error after deployment at build workzone

### Environment

Build Workzone

### What happened?

Hi Marian

From BAS we are able to deploy the application and we can see the preview of the application all good. But at the Build Workzone the application is not available. when we synced we got the below error regarding spreadsheet.

It was working good but when we did the redeployment we were facing this issue. Kindly respond as early as possible.

"AppId_cc.spreadsheetimporter.v0_33_4": {
**"error": [
"Replication failed for HTML5** app 'zmacreditdebitrequest' and manifest 'thirdparty/customControl/spreadsheetImporter/v0_33_4/manifest.json'",
**"Service name 'spreadsheetimporter_v0_33_4' and public setting 'true' in embedded manifest.json have to be equal to service name 'ManualAdjustment' and public setting 'true' of root manifest.json"**
],
"warning": []
}
![Error_Spreadsheet_at Workzone2](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/168772720/aea208c2-05e1-4783-872f-3adaecff5915)

Thank you.
![Error_Spreadsheet_at Workzone](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/168772720/25ea19fe-14b6-4415-9d19-1040fe86ad56)

### Relevant log output

```shell
We are facing error attached screen shot at SAP build workzone and when we try to sync to see the deployed application. Application is not available then we clicked on Report it has given this JSON log file attached.
```

### Spreadsheet Component Init

```js
We are facing error attached screen shot at SAP build workzone and when we try to sync to see the deployed application. Application is not available then we clicked on Report it has given this JSON log file attached.
```

**Comment by RaghavendraMarelle** [comment]
Hi Marian, can you please check and let us know as soon as possible. Thank you.

**Comment by marianfoo** [comment]
Hi,
as i already said in https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/issues/544#issuecomment-2139310466 that you should deploy the component not in the app but standalone as described in: https://docs.spreadsheet-importer.com/pages/CentralDeployment/

If you still like to deploy that inapp please create a ticket with SAP and kindly report back what SAP responds.
