### ISSUE TITLE
[Bug]: Forced refresh is not applicable for ODataV4

### ISSUE THREAD

**Issue by thecoldstone** [spreadsheetimporter/ui5-cc-spreadsheetimporter#589]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements/ObjectPage

### Environment

NVim 

### UI5 Spreadsheet Component

v1_1_1

### What happened?

Component is trying to refresh context for the page but fails due to the fact that ODataV4 does not support force refresh.

### Relevant log output

```shell
//Function below which causes error due to wrong passed parameter
ODataBinding.prototype.refresh = function (sGroupId) {
		if (typeof sGroupId === "boolean") {
			throw new Error("Unsupported parameter bForceUpdate");
		}
		this.requestRefresh(sGroupId).catch(this.oModel.getReporter());
};
```

### Spreadsheet Component Init

```js
export async function openSpreadsheetImportDialog(this: ExtensionAPI) {
	const view = this.getRouting().getView();
	const controller = view.getController() as BaseController;
	view.setBusyIndicatorDelay(0);
	view.setBusy(true);
	const spreadsheetImport = (await controller.getAppComponent().createComponent({
		usage: "spreadsheetImporter",
		async: true,
		componentData: {
			context: this,
			activateDraft: true,
			fieldMatchType: "label"
		}
	})) as Component;

	spreadsheetImport.openSpreadsheetUploadDialog();
	view.setBusy(false);
}
```

**Comment by marianfoo** [comment]
@thecoldstone  thank you for your bug report.
Might take a while till i can have a look at it. as a workaround you can refresh it yourself when the request is complete:
https://docs.spreadsheet-importer.com/pages/Events/#event-when-the-request-is-completed

**Comment by marianfoo** [comment]
@thecoldstone does #596 help? please check
