### ISSUE TITLE
[Bug]: "pnpm build:mta" fails with "Could not find custom task ui5-task-zipper"

### ISSUE THREAD

**Issue by stockbal** [spreadsheetimporter/ui5-cc-spreadsheetimporter#590]
### OData Version

no OData Service related

### Draft

not relevant

### Scenario

Central deployment 

### Environment

SAP BTP Workzone 

### UI5 Spreadsheet Component

v1.0.0

### What happened?

I checked out the repository at tag v1.0.0 and performed the described steps for central deployment

```shell
pnpm install
pnpm build:mta
```

After adding the dependency `ui5-task-zipper` to `ui5-cc-spreadsheetimporter` the mta build works without any issues.

### Relevant log output

```shell
[2024-07-09 09:38:55]  INFO executing the "npm run build:cf" command...

> ui5-cc-spreadsheetimporter@1.0.0 build:cf
> ui5 build --config=ui5-deploy-cf.yaml --all --clean-dest --dest dist

.info ProjectBuilder Preparing build for project ui5-cc-spreadsheetimporter
info ProjectBuilder   Target directory: dist

⚠️  Process Failed With Error

Error Message:
Could not find custom task ui5-task-zipper, referenced by project ui5-cc-spreadsheetimporter in project graph with root node ui5-cc-spreadsheetimporter

For details, execute the same command again with an additional '--verbose' parameter
[2024-07-09 09:38:57] ERROR could not build the "spreadsheetimporter" module: could not execute the "npm run build:cf" command: exit status 1
make: *** [Makefile_20240709093854.mta:37: spreadsheetimporter] Error 1
[2024-07-09 09:38:57] ERROR could not build the MTA project: could not execute the "make -f Makefile_20240709093854.mta p=cf mtar=archive strict=true mode=" command: exit status 2
Error: could not build the MTA project: could not execute the "make -f Makefile_20240709093854.mta p=cf mtar=archive strict=true mode=" command: exit status 2
/home/stockbal/development/projects/other/ui5-cc-spreadsheetimporter/packages/ui5-cc-spreadsheetimporter:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ui5-cc-spreadsheetimporter@1.0.0 build:mta: `rimraf resources mta_archives && mbt build --mtar archive`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

### Spreadsheet Component Init

```js
Not relevant yet
```

**Comment by marianfoo** [comment]
@stockbal thank you for trying this approach, the dependency is missing here, does that work when you add [`ui5-task-zipper`](https://www.npmjs.com/package/ui5-task-zipper) to the package.json of the spreadsheet importer package?

Also, do you think a carrier app like i did with the [abap deployment](https://docs.spreadsheet-importer.com/pages/CentralDeployment/#ui5-carrier-app) could work with BTP?
That would make the deployment maybe easier?

**Comment by stockbal** [comment]
Yes, adding `ui5-task-zipper` to the package.json is enough to get it working.  

Regarding the carrier app I am not sure. So you have here one application that embeds every version of the spreadsheet importer component and makes it available for other UI5 apps deployed to the ABAP system?

**Comment by marianfoo** [comment]
i fixed the missing dependency
if you have more ideas you are more then welcome to reach out
especially if you have a way for easier deployment and/or usage into BTP
