### ISSUE TITLE
[Bug]: Exclude columns configuration doesn't exist

### ISSUE THREAD

**Issue by albertoenriqueznews** [spreadsheetimporter/ui5-cc-spreadsheetimporter#622]
### OData Version

OData V4

### Draft

not relevant

### Scenario

Can't use excludeColumns feature

### Environment

BAS

### UI5 Spreadsheet Component

0_31_3

### What happened?

Im trying to use excludeColumns feature from the docs but its not working and cant find any reference of it in the whole library. 

### Relevant log output

```shell
Not excluding columns.
```

### Spreadsheet Component Init

```js
this.spreadsheetUpload = await this.getView()
          .getController()
          .getAppComponent()
          .createComponent({
            usage: "spreadsheetImporter",
            async: true,
            componentData: {
              context: this.base,
              createActiveEntity: false,
              spreadsheetFileName: "contribution_template.xlsx",
              i18nModel: this.getView().getModel("i18n"),
              excludeColumns: columnsToExclude,
              sampleData,
              showOptions: true,
              mandatoryFields,
            },
          });
```

### Manifest

```json
"resourceRoots": {
      "cc.spreadsheetimporter.v0_31_3": "./spreadsheetimporter"
    },
    "componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v0_31_3"
      }
    }
```

**Comment by marianfoo** [comment]
That feature was introduced with version 1.1.0:
https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/compare/ui5-cc-spreadsheetimporter-v1.0.0...ui5-cc-spreadsheetimporter-v1.1.0
