### ISSUE TITLE
[Bug]:Cannot load ui5-cc-spreadsheetimporter in SBWZ

### ISSUE THREAD

**Issue by dimdusart** [spreadsheetimporter/ui5-cc-spreadsheetimporter#636]
### OData Version

no OData Service related

### Draft

No

### Scenario

Freestyle

### Environment

BTP Workzone

### UI5 Spreadsheet Component

1.4.1

### What happened?

Hello Marian, first of all congrats for your work on this module.

I followed the implementation with Central Deployment for the spreadsheet importer. I followed all steps (with pnpm command), and the module seems well installed on my Cloud Foundry space.

![Image](https://github.com/user-attachments/assets/91dc12d4-570c-4100-81d9-cd331d8ebdf9)

I also changed the destination as indicated to link components inside a same CF space, to match the one of my consuming app in mta.yaml.

However, when I try to implement the component in my Freestyle app, I stumble each time on a 404 issue and fail to load the dependancy. I tried to reproduce the steps and be as close as your example files and documentation, but nothing seems to work for me.

I have my app deployed on Cloud Foundry as well and is setted inside SAP Build WorkZone Standard edition. I can access and run the app normally without calling the component.

In the manifest.json if it try to add 

```
"components": {
        "cc.spreadsheetimporter.v0_29_1": {}
      }
```
under `sap.ui5` and `dependancies`, the app won't load as to tell me there is no descriptor found for the spreadsheetimporter module.

For info I also added the dependancy in my package.json but with no better result : 

```
{
    "name": "sap.ibpm.createpr",
    "version": "0.0.1",
    "devDependencies": {
        "@sap/ui5-builder-webide-extension": "1.0.x",
        "@sap/ux-ui5-tooling": "^1",
        "@sapui5/ts-types": "1.71.x",
        "@ui5/cli": "^4.0.0",
        "@ui5/linter": "^0.2.6",
        "bestzip": "2.1.4",
        "mbt": "^1.2.18",
        "rimraf": "^4.0.0",
        "ui5-task-btp-manifest": "^0.2.2",
        "ui5-task-zipper": "^3.1.4"
    },
    "dependencies": {
        "ui5-cc-spreadsheetimporter": "1.4.1"
    },
    "scripts": {
        "zip": "cd dist && npx bestzip ../CreatePR-content.zip *",
        "clean": "npx rimraf CreatePR-content.zip dist",
        "build_old": "ui5 build --clean-dest --include-task=generateManifestBundle generateCachebusterInfo && npm run zip",
        "start": "fiori run --open \"test/flpSandbox.html?sap-ui-xx-viewCache=false#PurchaseRequisition-Create\"",
        "start-noflp": "fiori run --open \"index.html?sap-ui-xx-viewCache=false\"",
        "start-variants-management": "fiori run --open \"preview.html?fiori-tools-rta-mode=true&sap-ui-rta-skip-flex-validation=true&sap-ui-xx-condense-changes=true#preview-app\"",
        "build": "ui5 build -a --clean-dest --include-task=generateCachebusterInfo",
        "deploy": "fiori verify",
        "deploy-config": "fiori add deploy-config",
        "suite-tests": "fiori run --open 'test/testsuite.qunit.html'",
        "unit-tests": "fiori run --open 'test/unit/unitTests.qunit.html'",
        "int-tests": "fiori run --open 'test/integration/opaTests.qunit.html'",
        "build:cf": "ui5 build preload --all --clean-dest --config ui5-deploy.yaml --include-task=generateCachebusterInfo"
    },
    "ui5": {
        "dependencies": [
            "@sap/ui5-builder-webide-extension",
            "ui5-task-zipper",
            "mbt",
            "ui5-cc-spreadsheetimporter"
        ]
    },
    "private": true,
    "sapuxLayer": "CUSTOMER_BASE",
    "description": "",
    "keywords": [
        "ui5",
        "openui5",
        "sapui5"
    ],
    "main": "webapp/index.html"
}
```

and my `ui5-deploy.yaml` file is with `ui5-task-zipper` also : 

```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json
specVersion: '2.4'
metadata:
  name: sap.ibpm.CreatePR
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  resources:
    excludes:
      - "/test/**"
      - "/localService/**"
  customTasks:
  - name: webide-extension-task-updateManifestJson
    afterTask: replaceVersion
    configuration:
      appFolder: webapp
      destDir: dist
  - name: ui5-task-btp-manifest
    afterTask: replaceVersion
  - name: ui5-task-zipper
    afterTask: generateCachebusterInfo
    configuration:
      archiveName: CreatePR-content
      includeDependencies:
      - ui5-cc-spreadsheetimporter
      additionalFiles:
      - xs-app.json
```

### Relevant log output

Log-dbg.js:497 
 2024-10-03 14:58:53.117500 App 'sap.ibpm.CreatePR' has errors and will possibly not run properly -  sap.ibpm.CreatePR
Log-dbg.js:497 
 2024-10-03 14:58:53.118099 Error in application dependency 'cc.spreadsheetimporter.v1_4_1': No descriptor was found -  sap.ibpm.CreatePR
Log-dbg.js:497 
 2024-10-03 14:58:55.728699 sap/base/i18n/ResourceBundle: value for parameter 'aArgs' is not of type array -  
Log-dbg.js:497 
 2024-10-03 14:58:57.103899 failed to load JavaScript resource: cc/spreadsheetimporter/v1_4_1/Component-preload.js -  sap.ui.ModuleSystem
ui5loader-dbg.js:1426 
 
 GET https://sapui5.hana.ondemand.com/1.128.1/resources/cc/spreadsheetimporter/v1_4_1/Component.js 404 (Not Found)
Log-dbg.js:497 
 2024-10-03 14:58:57.215500 [FUTURE FATAL] Failed to load component for container application-purchaseRequest-create-component---Main--test - ModuleError: failed to load 'cc/spreadsheetimporter/v1_4_1/Component.js' from https://sapui5.hana.ondemand.com/1.128.1/resources/cc/spreadsheetimporter/v1_4_1/Component.js: 404  
 ModuleError: failed to load 'cc/spreadsheetimporter/v1_4_1/Component.js' from https://sapui5.hana.ondemand.com/1.128.1/resources/cc/spreadsheetimporter/v1_4_1/Component.js: 404
    at ve (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:6909)
    at he.failWith (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:4785)
    at Ie (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:13797)
    at Oe (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:15818)
    at Object.r [as require] (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:19302)
    at https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:457:36683
    at new Promise (<anonymous>)
    at https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:457:36650
Caused by: XHRLoadError: 404
    at n (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:9515)
    at XMLHttpRequest.<anonymous> (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:9768)
    at Le (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:9860)
    at Ie (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:13772)
    at Oe (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:15818)
    at Object.r [as require] (https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:15:19302)
    at https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:457:36683
    at new Promise (<anonymous>)
    at https://sapui5.hana.ondemand.com/1.128.1/resources/sap/fiori/appruntime-min-0.js:457:36650
Caused by: XHRLoadError: 404
    at n (ui5loader-dbg.js:1403:12)
    at XMLHttpRequest.<anonymous> (ui5loader-dbg.js:1416:21)
    at Le (ui5loader-dbg.js:1426:8)
    at Ie (ui5loader-dbg.js:1710:5)
    at Oe (ui5loader-dbg.js:1913:20)
    at Object.r [as require] (ui5loader-dbg.js:2184:4)
    at Component-dbg.js:3705:13
    at new Promise (<anonymous>)
    at Component-dbg.js:3703:12

### Spreadsheet Component Init

openSpreadsheetUploadDialog: async function (event) {
            this.getView().setBusyIndicatorDelay(0);
            this.getView().setBusy(true);
            this.spreadsheetUpload = await this.getView()
              .getController()
              .getAppComponent()
              .createComponent({
                usage: "spreadsheetImporter",
                async: true,
                componentData: {
                  context: this,
                },
              });
            this.spreadsheetUpload.openSpreadsheetUploadDialog();
            this.getView().setBusy(false);
        },

### Manifest

{
    "_version": "1.12.0",
    "sap.app": {
        "id": "sap.ibpm.CreatePR",
        "type": "application",
        "i18n": "i18n/i18n.properties",
        "applicationVersion": {
            "version": "1.1.1"
        },
        "title": "{{appTitle}}",
        "description": "{{appDescription}}",
        "resources": "resources.json",
        "sourceTemplate": {
            "id": "html5moduletemplates.basicSAPUI5ApplicationProjectModule",
            "version": "1.40.12",
            "toolsId": "271fe80b-cdbc-4990-98e7-c0044ea92b10"
        },
        "crossNavigation": {
            "inbounds": {
                "intent1": {
                    "signature": {
                        "parameters": {},
                        "additionalParameters": "allowed"
                    },
                    "semanticObject": "purchaseRequest",
                    "action": "create",
                    "title": "{{appTitle}}",
                    "info": "{{appDescription}}",
                    "subTitle": "",
                    "icon": "sap-icon://add"
                }
            }
        }
    },
    "sap.cloud": {
        "public": true,
        "service": "PurchaseRequisitionApproval"
    },
    "sap.ui": {
        "technology": "UI5",
        "icons": {
            "icon": "",
            "favIcon": "",
            "phone": "",
            "phone@2": "",
            "tablet": "",
            "tablet@2": ""
        },
        "deviceTypes": {
            "desktop": true,
            "tablet": true,
            "phone": true
        }
    },
    "sap.ui5": {
        "flexEnabled": false,
        "rootView": {
            "viewName": "sap.ibpm.CreatePR.view.Main",
            "type": "XML",
            "async": true,
            "id": "Main"
        },
        "dependencies": {
            "minUI5Version": "1.120.18",
            "libs": {
                "sap.ui.core": {},
                "sap.m": {},
                "sap.ui.layout": {}
            }
        },
        "contentDensities": {
            "compact": true,
            "cozy": true
        },
        "models": {
            "i18n": {
                "type": "sap.ui.model.resource.ResourceModel",
                "settings": {
                    "bundleName": "sap.ibpm.CreatePR.i18n.i18n"
                }
            },
            "": {
                "type": "sap.ui.model.json.JSONModel",
                "uri": "model/PR_StartApproval.json",
                "settings": {
                    "defaultBindingMode": "TwoWay"
                }
            }
        },
        "resources": {
            "css": [
                {
                    "uri": "css/style.css"
                }
            ]
        },
        "routing": {
            "config": {
                "routerClass": "sap.m.routing.Router",
                "viewType": "XML",
                "async": true,
                "viewPath": "sap.ibpm.CreatePR.view",
                "controlAggregation": "pages",
                "controlId": "app",
                "clearControlAggregation": false
            },
            "routes": [
                {
                    "name": "RouteMain",
                    "pattern": "RouteMain",
                    "target": [
                        "TargetMain"
                    ]
                }
            ],
            "targets": {
                "TargetMain": {
                    "viewType": "XML",
                    "transition": "slide",
                    "clearControlAggregation": false,
                    "viewId": "Main",
                    "viewName": "Main"
                }
            }
        },
        "componentUsages": {
            "spreadsheetImporter": {
                "name": "cc.spreadsheetimporter.v1_4_1"
            }
        }
    }
}

**Comment by marianfoo** [comment]
Hi @dimdusart ,

i am not that familiar with BTP deployment, but a few things i noticed:


This is not necessary, but only will preload the component.
If you want to use this then also correctly specify the version number like:
````
"components": {
        "cc.spreadsheetimporter.v1_4_1": {}
      }
````

This is not necessary anymore since UI5 Tooling v3:
````
    "ui5": {
        "dependencies": [
            "@sap/ui5-builder-webide-extension",
            "ui5-task-zipper",
            "mbt",
            "ui5-cc-spreadsheetimporter"
        ]
    },
````

If you use at direct dependency you need to use `resourceRoots` here, otherwise UI5 try to load the spreadsheetimporter from UI5 CDN:
https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-for-decentralized-deployment
```json
"resourceRoots": {
  "cc.spreadsheetimporter.v1_4_1": "./thirdparty/customcontrol/spreadsheetimporter/v1_4_1"
}
````

In the yaml file you need to add the version as well:
https://docs.spreadsheet-importer.com/pages/GettingStarted/#running-with-cap

```yaml
builder:
  customTasks:
    - name: ui5-task-zipper
      afterTask: generateComponentPreload
      configuration:
        archiveName: uimodule
        includeDependencies:
        - ui5-cc-spreadsheetimporter-v1-4-1
```

Please check this and try again

**Comment by dimdusart** [comment]
Hello @marianfoo,

It seems to work now, thanks ! Maybe there is a confusion for me from the doc, as I still don't quite get the difference between centralized and decentralized deployment. I wanted to use the recommended Central deployment, but not having the `ressourceRoots` indicated seems to not recognize the component even if deployed on BTP.
