### ISSUE TITLE
[Bug]: not all columns shown in preview

### ISSUE THREAD

**Issue by letuanngoc92** [spreadsheetimporter/ui5-cc-spreadsheetimporter#637]
### OData Version

OData V4

### Draft

No

### Scenario

Object Page/List Report

### Environment

FLP On Premise

### UI5 Spreadsheet Component

v1_4_1

### What happened?

I am experiencing an issue with the Excel template I created, which has three columns: CreateFlag, UpdateFlag, and DeleteFlag. I fill in the CreateFlag in the first row and then the UpdateFlag in the second row. However, the preview only displays the CreateFlag column.

I suspect that the code is identifying the number of columns for the preview based on the first row.

Could you please advise on how to resolve this issue?

### Relevant log output

I am experiencing an issue with the Excel template I created, which has three columns: CreateFlag, UpdateFlag, and DeleteFlag. I fill in the CreateFlag in the first row and then the UpdateFlag in the second row. However, the preview only displays the CreateFlag column.

I suspect that the code is identifying the number of columns for the preview based on the first row.

Could you please advise on how to resolve this issue?

### Spreadsheet Component Init

openSpreadsheetUploadDialog: async function (oEvent) {
			MessageToast.show("Custom handler invoked.");
			this._view.setBusyIndicatorDelay(0);
			this._view.setBusy(true);

			// prettier-ignore
			this.spreadsheetUpload = await this._view
				.getController()
				.getAppComponent()
				.createComponent({
					usage: "spreadsheetImporter",
					async: true,
					componentData: {
						context: this,
						createActiveEntity: false,
						i18nModel: this.getModel("i18n"),
						fieldMatchType: "label",
						spreadsheetFileName: "Kanban_Upload.xlsx",
						columns: ["CreateFlag", "UpdateFlag", "DeleteFlag", "Product", "ProductionSupplyArea", "Plant",
							"KanbanControlCycleCategory", "NumberOfKanbanContainers", "KanbanContainerQuantityInBsUnt",
							"MaxNrOfEmptyKanbanContainers", "KanbanContainerPackggProduct",
							"KanbanCtnReplnmtTriggerLogic", "KanbanCardPrintControl", "ProdnSupplySpoolOutputDevice",
							"StockTransferFlag", "Warehouse", "StorageType", "StorageBin", "StockTransferReplnmtStrategy",
							"StorageLocation", "SourceProductionSupplyArea", "SFGFlag", "InHouseProductionReplnmtStrgy",
							"SupplySourceResponsiblePerson", "ProductionVersion",
							"ExtSupplyFlag", "ExtProcurementReplnmtStrgy", "PurchaseOutlineAgreement",
							"PurchaseOutlineAgreementItem", "PurchasingOrganization", "Supplier",
							"KanbanCtnCalcSafetyFactor", "BaseUnit", "KanbanCtnRoundingQtyInBsUnt",
							"ReplnmtLeadTimeInHoursAndMins", "KanbanContainerCalcProfile", "CostCenter",
							"KanbanContainerStatusSequence"
						],
						sampleData: [
							{
								CreateFlag: "X",
								Product: "FG_KANBAN_GR",
								ProductionSupplyArea: "M2S-03",
								Plant: "333D",
								KanbanControlCycleCategory: 'K',
								NumberOfKanbanContainers: "2",
								KanbanContainerQuantityInBsUnt: "1",
								InHouseProductionReplnmtStrgy: "9000",
								SupplySourceResponsiblePerson: "ZZZ",
								BaseUnit: "PC"
							}
						]
					}
				});

				this.spreadsheetUpload.attachCheckBeforeRead(function (event) {
					// example
					/*const sheetdata = event.getParameter("sheetData");
					let errorArray = [];
					for (const [index, row] of sheetdata.entries()) {
						// Check createFlag, updateFlag và deleteFlag
						const createFlag = row['CreateFlag'] ? row['CreateFlag'].rawValue : null;
						const updateFlag = row['UpdateFlag'] ? row['UpdateFlag'].rawValue : null;
						const deleteFlag = row['DeleteFlag'] ? row['DeleteFlag'].rawValue : null;
				
						// If all is empty
						if (!createFlag && !updateFlag && !deleteFlag) {
							const error = {
								title: "All flags are empty (createFlag, updateFlag, deleteFlag)",
								row: index + 2,
								group: true,
								ui5type: "Error"
							};
							errorArray.push(error);
						}
					}
					event.getSource().addArrayToMessages(errorArray);*/
				}, this);

			this.spreadsheetUpload.openSpreadsheetUploadDialog();
			this._view.setBusy(false);
		}

### Manifest

"resourceRoots": {
      "cc.spreadsheetimporter.v1_4_1": "./thirdparty/customcontrol/spreadsheetimporter/v1_4_1"
    },
    "componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v1_4_1"
      }
    },

**Comment by marianfoo** [comment]
Thank you for the bug report!
fix with version 1.4.2
