### ISSUE TITLE
[FEAT]: Disabling batch requests

### ISSUE THREAD

**Issue by schaiet** [spreadsheetimporter/ui5-cc-spreadsheetimporter#662]
Hello :)

I am currently working on a project, in which I want to have access of all the entries in a sheet in my POST handler. Right now, when I use your plugin, a batch request is generated and for each entry a separate POST is triggered. Because of the parallel processing I cannot tell if the same entry part has been inserted already or not. This has created the issue, that on error it rolls back the whole POST. The data looks something like this:

param1,param2,param3
A,A,A
A,A,B

The first two parameters needs to be stored in one table and the third parameters in other one. 
I found the option "batchSize" and figured, if I set it to 0 no batch request is created and I could handle my data in my POST handler easily in the backend. Upon further reading I realised it will be at least one batch request at all times.
My proposal is to introduce a new option, which allows to disable the batching, so I can handle the data in my backend accordingly.
Do you plan it to introduce it in the community version or accept pull requests for this feature?

Best Regards,
Tanja

**Comment by marianfoo** [comment]
Great it worked out for you :)
