### ISSUE TITLE
[Bug]: In standalone mode a spreadsheetTemplateFile should work without having to define columns

### ISSUE THREAD

**Issue by MARCxGAMBIT** [spreadsheetimporter/ui5-cc-spreadsheetimporter#692]
### OData Version

OData V2

### Draft

No

### Scenario

Fiori Elements List Report

### Environment

FLP On Premise

### UI5 Spreadsheet Component

1.4.3

### What happened?

I have a standalone scenario where I want to provide a template which allows deep upload (basically two sheets, first sheet is uploaded first, after that for each parent context I create and upload the child context from the second sheet).

I set the following config:

```
readAllSheets: true,
standalone: true,
spreadsheetTemplateFile: "my/namespace/bin/template.xlsx",
```

The "Download Template" button is still hidden. So I provided a columns setting `columns: []`. Button still hidden. So I added dummy columns. Button visible, template downloadable.

Could the availability of a spreadsheetTemplateFile be considered when calculating the visibility of the "Download Template" button?

### Relevant log output

```shell
-
```

### Spreadsheet Component Init

```js
columns: ["Dummy"],
hidePreview: true,
fieldMatchType: "label",
readAllSheets: true,
standalone: true,
spreadsheetTemplateFile: "my/namespace/bin/template.xlsx",
```

### Manifest

```json

```

**Comment by marianfoo** [comment]
Thank you @MARCxGAMBIT for the Bug Report and PR.
Fix is released with version [`1.6.0`](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/releases/tag/ui5-cc-spreadsheetimporter-v1.6.0)
